ENABLE_LINTERS:
  - standard      # 
  - CSHARP_DOTNET_FORMAT # C#
  - SQL_SQLFLUFF      # SQL
  - SQL_SQL_LINT      # SQL
  # GitHub Actions and YAML
  - ACTION_ACTIONLINT
  - YAML_YAMLLINT
  # Clones and Duplicates
  - COPYPASTE_JSCPS
  # Shell/Bash
  - BASH_EXEC
  - BASH_SHFMT
  - BASH_SHELLCHECK
  # WEB
  - CSS_STYLELINT     # CSS
  - CSS_SCSS_LINT     # SCSS
  - HTML_HTMLHINT     # HTML
  - JAVASCRIPT_STANDARD # JS
  - JAVASCRIPT_ES
  - JSON_JSONLINT     # JSON
  - XML_XMLLINT       # XML

# ANSIBLE_ANSIBLE_LINT, ARM_ARM_TTK,
# COPYPASTE_JSCPD, CPP_CPPLINT, CREDENTIALS_SECRETLINT, 
# C_CPPLINT,
# EDITORCONFIG_EDITORCONFIG_CHECKER, ENV_DOTENV_LINTER,
# GRAPHQL_GRAPHQL_SCHEMA_LINTER, JAVASCRIPT_PRETTIER,
# JSON_ESLINT_PLUGIN_JSONC, JSON_PRETTIER, JSON_V8R, JSX_ESLINT, 
# LATEX_CHKTEX, LUA_LUACHECK, 
# OPENAPI_SPECTRAL, POWERSHELL_POWERSHELL, 
# PYTHON_BANDIT, PYTHON_BLACK, PYTHON_FLAKE8, PYTHON_ISORT, PYTHON_MYPY, PYTHON_PYLINT, RAKU_RAKU, RST_RSTCHECK, 
# RST_RSTFMT, RST_RST_LINT, SPELL_CSPELL, SPELL_MISSPELL, 
# TSX_ESLINT, YAML_PRETTIER, YAML_V8R
To receive reports as email, please set variable EMAIL_REPORTER_EMAIL
